Ewelyn: Desafio semana 2 POO Banco Comunitário
reprograma/on32-ijs-s2-poo pull request #12
Opened 2024-06-27 23:08 UTC by ewelyn-samaris

Esse PR adiciona enums, interfaces e models para criação das entidades de cliente, banco, contas, requisição de cliente e transação referentes à aplicação Banco comunitário.

2024-07-01 02:41 UTC, daiisntos requested changes

2024-07-01 02:41 UTC, daiisntos commented on exercicios/para-casa/entregas/ewelyn-samaris/models/Bank.model.ts
> +            throw new Error(message);
It would be interesting to use a try catch to handle any exception.

2024-07-01 02:41 UTC, daiisntos commented on exercicios/para-casa/entregas/ewelyn-samaris/models/CustomerRequest.model.ts
> +import { v4 as uuidv4 } from 'uuid';
Cool, I didn't know that TS used uuid

2024-07-01 02:41 UTC, daiisntos commented on exercicios/para-casa/entregas/ewelyn-samaris/models/SavingAccount.model.ts
> +    deposit(value: number): void {
I think this point can be improved and kept the code cleaner, here is a suggestion: 
deposit(value: number): void {
    const status = value < this.MINIMUN_TO_DEPOSIT ? TransactionStatus.ERROR : TransactionStatus.SUCCESS;
    const transaction = new Transaction(TransactionType.DEPOSIT, status, value, this.balance);

    if (status === TransactionStatus.SUCCESS) {
        this.accountBalance += value;
    }

    this.transactionHistory.push(transaction);
}
If it makes sense to you

2024-07-03 02:21 UTC, isjanebea commented
:nail_care: arrasou :purple_heart:

2024-09-14 15:32 UTC, closed without merging